spring.application.name=backend

## db
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/portfolio}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dev}

## hibernate
spring.jpa.hibernate.ddl-auto=validate

## oauth2
spring.security.oauth2.client.registration.github.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
app.admin-email=${APP_ADMIN_EMAIL}