spring.application.name=backend

## db
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/portfolio}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:dev}

## hibernate
spring.jpa.hibernate.ddl-auto=validate

## oauth2
spring.security.oauth2.client.registration.github.client-id=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
app.admin-email=${APP_ADMIN_EMAIL}

## file-storage
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

## r2
r2.endpoint=${R2_ENDPOINT}
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_KEY}
r2.bucket=${R2_BUCKET}
r2.public-base=${R2_PUBLIC_BASE}
r2.region=${R2_REGION}

## deployment
server.port=${PORT:8080}
app.frontend-url=${APP_FRONTEND_URL:http://localhost:3000}